window.LANG = {
    gameTitle: 'Космический Шутер',
    score: 'Счёт',
    coins: 'Монеты',
    level: 'Уровень',
    pauseTitle: 'Пауза',
    pauseHint: 'Нажмите ESC чтобы продолжить',
    deathTitle: 'Игра окончена',
    deathCoins: 'Получено монет',
    restart: 'Заново',
    mainMenu: 'Главное меню',
    arcadeMode: 'Бесконечный режим',
    levelsMode: 'Уровни',
    levelSelect: 'Выбор уровня',
    shop: 'Магазин',
    profile: 'Профиль',
    shopSkins: 'Скины',
    shopDrones: 'Дроны',
    back: 'Назад',
    nextLevel: 'Следующий уровень',
    levelComplete: 'Уровень пройден!',
    coinsEarned: 'Получено монет',
    standard: 'Стандартный',
    free: 'Бесплатно',
    soon: 'Скоро',
    select: 'Выбрать',
    selected: 'Выбран',
    buy: 'Купить',
    owned: 'Куплено',
    upgrade: 'Улучшить',
    bossLevel: 'БОСС',
    gameOver: 'ИГРА ОКОНЧЕНА',
    playerLevel: 'Уровень пилота',
    experience: 'Опыт',
    droneSlots: 'Слоты дронов',
    slotsOpen: 'открыто',
    slotLocked: 'Закрыт',
    slotOpen: 'Открыт',
    requiredLevel: 'Нужен уровень',
    unlockSlot: 'Открыть слот',
    equipped: 'В бою',
    notEquipped: 'Не выбран',
    pilotName: 'Имя пилота',
    rank: 'Ранг',
    gear: 'Снаряжение',
    statistics: 'Статистика',
    levelsCompleted: 'Пройдено уровней',
    totalScore: 'Общий счёт',
    editName: 'Изменить имя',
    page: 'Страница',
    droneStats: { hp: 'HP', damage: 'Урон', fireRate: 'Скорость', special: 'Особенность' },
    droneDescriptions: {
        defender: 'Универсальный помощник. Стреляет по ближайшим врагам.',
        interceptor: 'Быстрый дрон. Приоритет — быстрые враги.',
        heavy: 'Мощный дрон. Стреляет залпами, много HP.',
        healer: 'Не атакует. Восстанавливает 1 HP раз в 30 сек.'
    },
    ranks: {
        recruit: '🎖️ Новобранец',
        cadet: '⭐ Кадет',
        lieutenant: '🌟 Лейтенант',
        captain: '💫 Капитан',
        commander: '👑 Командор'
    }
};