window.LANG = {
    gameTitle: 'Космический Шутер',
    score: 'Счёт',
    coins: 'Монеты',
    level: 'Уровень',
    pauseTitle: 'Пауза',
    pauseHint: 'Нажмите ESC чтобы продолжить',
    deathTitle: 'Вы погибли',
    deathCoins: 'Получено монет',
    restart: 'Заново',
    mainMenu: 'Главное меню',
    arcadeMode: 'Бесконечный режим',
    campaignMode: 'Кампания',
    levelSelect: 'Выбор уровня',
    skins: 'Скины',
    back: 'Назад',
    nextLevel: 'Следующий уровень',
    levelComplete: 'Уровень пройден!',
    coinsEarned: 'Получено монет',
    standard: 'Стандартный',
    free: 'Бесплатно',
    soon: 'Скоро',
    select: 'Выбрать',
    selected: 'Выбран',
    bossLevel: 'БОСС'
};