window.DOM = {};
window.cacheDOMElements = function() {
    DOM.sidebar = document.querySelector('.sidebar');
    DOM.mainContent = document.querySelector('.main-content');
    DOM.ui = document.getElementById('ui');
    DOM.homeView = document.getElementById('homeView');
    DOM.levelsView = document.getElementById('levelsView');
    DOM.profileView = document.getElementById('profileView');
    DOM.shopView = document.getElementById('shopView');
    DOM.settingsView = document.getElementById('settingsView');
    DOM.deathScreen = document.getElementById('deathScreen');
    DOM.levelCompleteScreen = document.getElementById('levelCompleteScreen');
    DOM.pauseScreen = document.getElementById('pauseScreen');
    DOM.arcadeBtn = document.getElementById('arcadeBtn');
    DOM.levelPrevBtn = document.getElementById('levelPrevBtn');
    DOM.levelNextBtn = document.getElementById('levelNextBtn');
    DOM.mobilePauseBtn = document.getElementById('mobilePauseBtn');
    DOM.pauseResumeBtn = document.getElementById('pauseResumeBtn');
    DOM.pauseMenuBtn = document.getElementById('pauseMenuBtn');
    DOM.restartBtn = document.getElementById('restartBtn');
    DOM.menuBtn = document.getElementById('menuBtn');
    DOM.nextLevelBtn = document.getElementById('nextLevelBtn');
    DOM.levelCompleteMenuBtn = document.getElementById('levelCompleteMenuBtn');
};
console.log('main/dom-cache.js загружен');